spring.application.name=HospitalManagementSystem

#spring.datasource.url=jdbc:mysql://localhost:3306/maya_hospital
#spring.datasource.username=root
#spring.datasource.password=
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
# ====== JPA / Hibernate ======
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

#hii kutte

spring.security.user.name=rahul
spring.security.user.password=pass123

jwt.secretkey=${JWT_SECRET}